const ACTIONS = {
    UPDATE_GOODS : 'UPDATE_GOODS',
    SET_LOADING : "SET_LOADING",
    UPDATE_TOGGLE : 'UPDATE_TOGGLE',
    UPDATE_BASKET : 'UPDATE_BASKET',
    UPDATE_AMOUNT : 'UPDATE_AMOUNT',
    SET_AMOUNT: 'SET_AMOUNT',
    SET_NOTIFICATION: "SET_NOTIFICATION"
}

export { ACTIONS }
